CREATE TABLE characters (
    id SERIAL PRIMARY KEY,
    role TEXT,
    name TEXT,
    other_names TEXT,
    ethnicity TEXT,
    citizenship TEXT,
    birthdate DATE,
    parents TEXT,
    children TEXT,
    partners TEXT,
    religion TEXT,
    pronouns TEXT,
    sexuality TEXT,
    ideal_actor TEXT,
    alma_mater TEXT,
    major TEXT,
    occupation TEXT,
    affiliation TEXT,
    location TEXT,
    favorite_music TEXT,
    languages TEXT,
    halloween_costume TEXT,
    hobbies TEXT,
    hair TEXT,
    height TEXT,
    birthplace TEXT,
    smells_like TEXT,
    favorite_sports_team TEXT,
    appearances TEXT,
    death_date DATE,
    death_location TEXT,
    mental_conditions TEXT,
    username TEXT,
    middle_name TEXT,
    name_in_native_script TEXT
);
